services:
    postgres:
        image: postgres
        container_name: finance-app-postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: finance-app
        ports:
            - 5432:5432
        volumes:
            - ./.postgres:/var/lib/postgresql/data
