version: '3'

services:
    postgres:
        image: postgres:latest
        container_name: finance-app
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        volumes:
            - ./.postgres:/var/lib/postgresql/data
